import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Editor from '../components/Editor'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>interactive minimal IK</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='flex h-screen'>
        <div className='m-auto h-1/2 w-1/2 text-5xl'>
          <h1 className="text-center mb-5">interactive minimal IK</h1>
          <div className='border-2 h-full' id='editor-wrapper'>
            <Editor />
            {/* <div>hey</div> */}
          </div>
        </div>
      </div>
    </div>
  )
}

export default Home
